---
- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400

- name: Install Git
  become: true
  apt:
    name: git
    state: present

- name: Install Python and pip
  become: true
  apt:
    state: present
    update_cache: yes
    name:
      - python3
      - python3-pip
      - python3-setuptools


- name: Install UFW
  become: true
  apt:
    state: present
    name:
      - ufw